[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
numReplicas = 1
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port 8000"

[[services]]
name = "web"
[[services.ports]]
port = 8000